### ISSUE TITLE
GNU 9 compiler 

### ISSUE THREAD

**Issue by FeffyLaffy** [ZTzTopia/GTProxy#10]
is this working build with GNU 9?

**Comment by ZTzTopia** [comment]
All compilers that support c++20 can compile this source.

**Comment by FeffyLaffy** [comment]
![image](https://user-images.githubusercontent.com/74392505/173325356-28b54fea-33ca-4993-bf31-5a5b51bb0c2d.png)
![image](https://user-images.githubusercontent.com/74392505/173325502-a80dcbe2-7558-4bbe-a2d0-6178ed2e68c0.png)

weird error

**Comment by ZTzTopia** [comment]
looks like i fixed it in the latest commit
