### ISSUE TITLE
Redirecting issue

### ISSUE THREAD

**Issue by koftrciali** [ZTzTopia/GTProxy#22]
When Redirecting the growtopia client sends: PACKET_DISCONNECT
if proxy dont disconnects sometimes redirecting will not work to fix it:
if (game_update_packet->type == player::PACKET_DISCONNECT and m_client->is_redirecting()) {
            m_peer->disconnect_now();

  }
but it sometimes growtopia client says: Disconnted trying reconnect...
i dont know why

**Comment by ZTzTopia** [comment]
oh yeah, thanks I think it's because my internet is so bad I have to reconnect every time I can't connect to the server.
I will fix asap.

**Comment by koftrciali** [comment]
it sometimes froze in logining but world switching is fine

**Comment by aliersahan** [comment]
Remove this lines from server.cpp 

text_parse.set("game_version", m_config->m_server.game_version);
text_parse.set("protocol", m_config->m_server.protocol);

Tempoirly fix?

**Comment by ZTzTopia** [comment]
This commit https://github.com/ZTzTopia/GTProxy/commit/b523fee72b029970118c5d1d4d0f9491610e7bf7 should fix the redirecting issue.

**Comment by koftrciali** [comment]
yea surely this is asap
