### ISSUE TITLE
Game Update

### ISSUE THREAD

**Issue by EngShop** [ZTzTopia/GTProxy#24]
It is forcing me to update the game even tho i already have an updated version.

**Comment by ZTzTopia** [comment]
did u update the protocol from config.json?

**Comment by EngShop** [comment]
> did u update the protocol from config.json?

yes i already did updated it but it still prompts me with "UPDATE REQUIRED"

**Comment by koftrciali** [comment]
Remove this lines from server.cpp

text_parse.set("game_version", m_config->m_server.game_version);
text_parse.set("protocol", m_config->m_server.protocol);

Tempoirly fix?

**Comment by JadlionHD** [comment]
this should be fixed (#38)
