### ISSUE TITLE
Conan new update

### ISSUE THREAD

**Issue by FeffyLaffy** [ZTzTopia/GTProxy#29]
feel like conan got new version since i want build the project is failed check it out https://github.com/ZTzTopia/GTProxy/actions/runs/3807347178/jobs/6476949622#step:4:1224

**Comment by ZTzTopia** [comment]
Yes, [Conan](https://conan.io/) updated to version 2.0.0 and [cmake-conan](https://github.com/conan-io/cmake-conan) still not updated for [Conan](https://conan.io/) version 2.0.0.

**Comment by FeffyLaffy** [comment]
> Yes, [Conan](https://conan.io/) updated to version 2.0.0 and [cmake-conan](https://github.com/conan-io/cmake-conan) still not updated for [Conan](https://conan.io/) version 2.0.0.

yep is work using 1.55.0 conan version is working
