### ISSUE TITLE
after last edit error building

### ISSUE THREAD

**Issue by apol3t** [ZTzTopia/GTProxy#32]
here is the error building 

C:\Users\apolet\Desktop\proxy\GTProxy\src\server\server.cpp(150,91): error C2664: 'int player::Peer::send_packet(player::eNetM
essageType,const std::string &)' : 2 argument 'std::stringstream' from the value 'const std::string &' 
turned into value it can't be imagined [C:\Users\alper\Desktop\proxy\build\src\Source.vcxproj]

**Comment by FeffyLaffy** [comment]
try https://github.com/ZTzTopia/GTProxy/pull/33 i forget to convert string stream to string at warp packet
