### ISSUE TITLE
maintenance

### ISSUE THREAD

**Issue by Notfaked** [ZTzTopia/GTProxy#37]
When i try to start it it says server is under maintenance, we will be back shortly.
Is that normal or do i have to fix it by myself if that´s even possible

**Comment by majknez** [comment]
Wrong IP.

**Comment by Notfaked** [comment]
isnt ip the 127.0.0.1?

**Comment by majknez** [comment]
No thats only in the host files.

**Comment by majknez** [comment]
@ZTzTopia close this as well. cuz of no reply
