### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by ronlee31** [ZTzTopia/GTProxy#40]
Is it like Silvestras proxy that can be use to host a Casinos or not?

**Comment by ZTzTopia** [comment]
nope, I made this only for packet debugging for private server purposes. But who knows what will happen in the future?

**Comment by BirdyTheDev** [comment]
> nope, I made this only for packet debugging for private server purposes. But who knows what will happen in the future?

Hello Ztz i have issue currently cant connect server stuck on logging on any fixes out there?

**Comment by majknez** [comment]
Please be more specific @BirdyTheDev 
1. Did you edit host files
2. Did you edit the IP in the config.json

**Comment by BirdyTheDev** [comment]
> 

i already editied the hosts file 
whats ip in config.json to edit?

**Comment by BirdyTheDev** [comment]
its the config file 
{
    "command": {
        "prefix": "!"
    },
    "host": {
        "port": 16999
    },
    "misc": {
        "forceUpdateGameVersion": false
    },
    "server": {
        "gameVersion": "4.20",
        "host": "growtopia1.com",
        "protocol": 188
    }
}

**Comment by majknez** [comment]
host is the current ip of growtopia2.com
try 18.215.115.101 
put it in and reset proxy

**Comment by BirdyTheDev** [comment]
[2023-04-09 17:41:28.899] [GTProxy] [info] Starting Growtopia proxy v1.3.1+54...
[2023-04-09 17:41:28.901] [GTProxy] [info] HTTP(s) server listening on port 443.
[2023-04-09 17:41:29.502] [GTProxy] [error] Failed to get server data. HTTP status code: 403
[2023-04-09 17:41:30.103] [GTProxy] [error] Failed to get server data. HTTP status code: 403

{
    "command": {
        "prefix": "!"
    },
    "host": {
        "port": 16999
    },
    "misc": {
        "forceUpdateGameVersion": false
    },
  "server": {
    "gameVersion": "4.20",
    "host": "18.215.115.101",
    "protocol": 188
  }
}

**Comment by BirdyTheDev** [comment]
still getting error

**Comment by majknez** [comment]
You have to update ur proxy. Build the new one from source. The config file is different now platform id is required.

**Comment by BirdyTheDev** [comment]
> You have to update ur proxy. Build the new one from source. The config file is different now platform id is required.

okey let me update it

**Comment by BirdyTheDev** [comment]
yuppi working finaly thanks!

**Comment by BirdyTheDev** [comment]
im too dump lol forget to update it 🗡️  its working now

**Comment by majknez** [comment]
Its fine. Dont worry.

**Comment by Notfaked** [comment]
hello, i am new to all this and kinda feel dumb but how do u update a proxy?

**Comment by majknez** [comment]
You have to build it your self because the latest release is like 9 months old.

**Comment by Notfaked** [comment]
that´s the problem, i dont know anything about how u build it. i tried installing the zip files but idk what to do next. I already have visual studio but im lost

**Comment by majknez** [comment]
If you have discord i can help but i dont see a point of having a proxy if you have no knowledge. this proxy has no benefit only viewing packets (if you have no experience with coding)

**Comment by Notfaked** [comment]
oh ok ty for all info. i have tried to learn coding before but didn´t work as planned. I wanted to make a growtopia proxy yk like  those pro proxys but i dont think this is like one of them

**Comment by majknez** [comment]
Uh this one has a decent base. Without coding knowledge its gonna be impossible of making a proxy and its not only about the coding its about understanding the growtopia protocol(enet which is modified) , networking, https and some extra stuff.

**Comment by Notfaked** [comment]
ye i know. it´s just a waste to try to make this work because i have 0 coding knowledge but thanks for your help anyways

**Comment by majknez** [comment]
@ZTzTopia close this as well.
