### ISSUE TITLE
Proxy failing to fetch data

### ISSUE THREAD

**Issue by MrStretchd** [ZTzTopia/GTProxy#51]
I've tried it with different ip's but it seems not to work.

![image](https://user-images.githubusercontent.com/69754466/235936859-2a2a23fe-faea-457b-85b9-302ad127061a.png)

**Comment by ZTzTopia** [comment]
Looks like the ip is no longer valid, you can change new ip in `config.json`. You can use this new ip `52.72.16.239`.

**Comment by MrStretchd** [comment]
Hey! I assumed that was the problem but didn't know how I could get a new one. Thanks for the help ❤️

**Comment by ZTzTopia** [comment]
What do you mean how to get new one?

**Comment by MrStretchd** [comment]
How do you get the growtopia's server ip? Is it the same as the growtopia1.com domain IP?

**Comment by ZTzTopia** [comment]
Search on google with the keyword `domain to ip`

**Comment by MrStretchd** [comment]
The ip I get from the domain will not work. Which domain do you mean?

**Comment by JadlionHD** [comment]
> The ip I get from the domain will not work. Which domain do you mean?

`www.growtopia1.com` or `www.growtopia2.com`

**Comment by MrStretchd** [comment]
Hey! Neither of them seem to work.

**Comment by badewen** [comment]
fixed in #72
