### ISSUE TITLE
Growtopia update

### ISSUE THREAD

**Issue by MrStretchd** [ZTzTopia/GTProxy#52]
Hey! Growtopia received a new update today and the proxy is now not login in :(. Could I know what is the problem here? Thank you for the support on the last issue ❤️

**Comment by ZTzTopia** [comment]
I thought because of the login spoof, maybe Growtopia updated the key from the klv.

**Comment by koftrciali** [comment]
growtopia updated klv salts i have salts but i cant share
just remove login spof

**Comment by MrStretchd** [comment]
I deleted the whole login section in server.cpp but it still doesn't seem to work.

**Comment by koftrciali** [comment]
did u return true ?

**Comment by ZTzTopia** [comment]
#53
