### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by NonTaxx** [ZTzTopia/GTProxy#55]
Stuck with this
![image](https://user-images.githubusercontent.com/108197358/236868661-dccb6dda-9099-4958-99a3-49eb8d2c9e64.png)

**Comment by koftrciali** [comment]
klv salts updated ztz didnt updated proxy yet

**Comment by koftrciali** [comment]
and your problem is not login u didnt updated ip

**Comment by NonTaxx** [comment]
After updating everything it's the same issue.
![image](https://github.com/ZTzTopia/GTProxy/assets/108197358/3c52c3f1-fbc1-4cad-a08c-d34da666d5e8)

**Comment by koftrciali** [comment]
2.17.198.162

**Comment by badewen** [comment]
fixed in #72
