### ISSUE TITLE
Stuck on "Logging on [username]" for Growtopia Version 4.26

### ISSUE THREAD

**Issue by fmptg** [ZTzTopia/GTProxy#57]
I've been stuck on the "Logging on" screen for quite some time. Used the latest source code to build Proxy.exe but then it gets disconnected. Here is the output from Windows 11:
![image](https://github.com/ZTzTopia/GTProxy/assets/133398659/01a531a6-53d7-41cd-86af-f6f0c6340749)
![image](https://github.com/ZTzTopia/GTProxy/assets/133398659/5835a071-239d-4585-bbf0-e36dc2cc51de)
![issue1](https://github.com/ZTzTopia/GTProxy/assets/133398659/1203fbda-8529-4a51-8def-cdda2196abc2)
Thanks.

**Comment by koftrciali** [comment]
remove login spoff ztz didnt updated keys yet

**Comment by disomimbaryan** [comment]
what is the key

**Comment by ZTzTopia** [comment]
Fixed 771f2f63ebfc67c657a4f324e1f7589e4b2e8a9f
