### ISSUE TITLE
Not working in private server

### ISSUE THREAD

**Issue by caycun** [ZTzTopia/GTProxy#60]
Here's my config.json:
{
    "command": {
        "prefix": "!"
    },
    "host": {
        "port": 17007
    },
    "misc": {
        "forceUpdateGameVersion": false,
        "forceUpdateGameVersionProtocol": false
    },
    "server": {
        "gameVersion": "4.26",
        "host": "141.95.66.239",
        "platformID": "4",
        "protocol": 191
    }
}

and here is the CreativePS information got from 79.137.35.236/growtopia/server_data.php
server|141.95.66.239
port|17007
type|1
#maint|`$The CreativePS servers`` are under `#maintenance`` for launching Season 8 Update! `#Be right back...``
beta_server|beta.creativeps.eu
beta_port|16999
type2|0
beta_type|1
meta|Creative_175972843085195812681
RTENDMARKERBS1001

**Comment by badewen** [comment]
the "host" ip should be 79.137.35.236 or the CreativePS http server's ip. 
might make a PR to reduce confusion.
