### ISSUE TITLE
Nothing happening 

### ISSUE THREAD

**Issue by Laisvenzo** [ZTzTopia/GTProxy#62]
![image](https://github.com/ZTzTopia/GTProxy/assets/136497855/82c2f0d1-9ee9-422f-ad04-c59d25826a49)
even if i try logging in gt nothing happening
just outputs these commands when u turn it on and thats it
![image](https://github.com/ZTzTopia/GTProxy/assets/136497855/17f578e4-3cd0-4495-918d-ee46d7f52312)

**Comment by aliersahan** [comment]
gt updated but i sell fix dm me if realy need koftrciali#8433
