### ISSUE TITLE
Growtopia stuck on Login username

### ISSUE THREAD

**Issue by berkepak** [ZTzTopia/GTProxy#63]
I tried to pass login spoof as KLV salts might old still stuck on Login.
![image](https://github.com/ZTzTopia/GTProxy/assets/49535853/dcdfed58-d56e-450d-a192-1324035bf024)
![tempsnip](https://github.com/ZTzTopia/GTProxy/assets/49535853/ca41fb4a-849f-4198-bee9-ff9e1d30afcd)

**Comment by ZTzTopia** [comment]
Growtopia changed integrity of ENet headers, fixed in latest commit 002bd9a3cf33030ff2b3bffdc8b850eda4d3a802

**Comment by berkepak** [comment]
Thanks.
