### ISSUE TITLE
disconnected where update or get 404 on GTPS server

### ISSUE THREAD

**Issue by ArifRios1st** [ZTzTopia/GTProxy#69]
disconnected where update or get 404 on GTPS server
![image](https://github.com/ZTzTopia/GTProxy/assets/32938569/37debeae-cb04-43ec-aecb-4d7705c8c06b)

![image](https://github.com/ZTzTopia/GTProxy/assets/32938569/23e2417f-1e8b-40d0-97d6-6cf7eb75af94)

please help

**Comment by badewen** [comment]
is that the items.dat? becaue donwloading items.dat through the proxy will cause the growtopia to crash.

**Comment by ArifRios1st** [comment]
> is that the items.dat? becaue donwloading items.dat through the proxy will cause the growtopia to crash.

yes, it's item.dat, so i must update files first, then use proxy ?

**Comment by badewen** [comment]
yeah, you must download the items.dat without the proxy first. idk what is the problem causing growtopia to crash.
