### ISSUE TITLE
Unable to use the proxy

### ISSUE THREAD

**Issue by zix3r** [ZTzTopia/GTProxy#7]
Downloaded the binaries, and it's just stuck on this, and after a while it just closes:
![image](https://user-images.githubusercontent.com/43238887/171418990-83910d24-a713-4719-9e80-b30cc222d728.png)

**Comment by ZTzTopia** [comment]
You can use the latest release version. Let me know if the problem is resolved in the new release.

**Comment by zix3r** [comment]
Yep thanks, proxy is working fine now!
