### ISSUE TITLE
Error while try to build

### ISSUE THREAD

**Issue by Furkan125** [ZTzTopia/GTProxy#70]
Hi. I was also getting an error while running the command "cmake .. -DCMAKE_BUILD_TYPE=Debug" but I fixed the problem by changing the fmt version to 10.0.0 from the conanfile.py file.
"cmake --build ." I also get an error when I run the command and I don't know how to solve it.

Here is the error:
[message.txt](https://github.com/ZTzTopia/GTProxy/files/12265417/message.txt)

**Comment by badewen** [comment]
assuming from the MSBuild version, it seems like yours is outdated. try upgrading to 17.5.1 and/or try adding -DCMAKE_CXX_STANDARD=20. I can only assume though since mine is building properly

**Comment by Furkan125** [comment]
Does the version need to be 17.5.1 specifically? I am currently using the latest version and there is still an error.

[message.txt](https://github.com/ZTzTopia/GTProxy/files/12270314/message.txt)

Also, where should I add the "-CMAKE_CXX_STANDARD=20" command? There is already a similar in CMakeLists.txt.

**Comment by badewen** [comment]
It built succesfully??? Using google translate i didnt see any errors there.

**Comment by Furkan125** [comment]
No, no exe file is created after the command is run.
Cmake closes after "Generating code...".

![image](https://github.com/ZTzTopia/GTProxy/assets/58825170/6b74fc8d-52e0-4e26-9543-26b4b000f9ee)


![image](https://github.com/ZTzTopia/GTProxy/assets/58825170/db7027d0-4254-4c34-8483-d04d4d6a31a1)

**Comment by badewen** [comment]
Yeah the build env is fucked. Try deleting the "build" direcotory and revert the fmt version or any other version that you have changed.

**Comment by Furkan125** [comment]
I changed the version because I got an error when I left the fmt version the same.

I did what you said and when I run command "cmake .. -DCMAKE_BUILD_TYPE=Debug" I get this error:
[message.txt](https://github.com/ZTzTopia/GTProxy/files/12287268/message.txt)

**Comment by badewen** [comment]
Sorry for the late response, you have to change the fmt version to 9.1 since spdlog 1.11 is not compatible with fmt version 10.x.

**Comment by Furkan125** [comment]
That is the problem. While fmt version is 10.x, I do not get an error, but 9.1 gives an error.

[message.txt](https://github.com/ZTzTopia/GTProxy/files/12297170/message.txt)

**Comment by Furkan125** [comment]
I think I fixed it. My fmt version is 8.0.1 and spdlog version is 1.9.2 and I got the exe file.

**Comment by Furkan125** [comment]
Yes It builded. Thank you for help.
