### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by benardamorkoc** [ZTzTopia/GTProxy#76]
![image](https://github.com/ZTzTopia/GTProxy/assets/123625632/b12c8f24-b84e-4bd0-8070-09b493fc6456)

[info] The client just disconnected from the server at 213.179.209.168:17181!

**Comment by ZTzTopia** [comment]
Unfortunately i haven't finished creating this proxy yet, i want to continue but i'm still very busy 😅

**Comment by ZTzTopia** [comment]
I have finished version 2.0 maybe you can check it https://github.com/ZTzTopia/GTProxy/releases/tag/v2.0
