### ISSUE TITLE
error CMAKE_PROJECT_TOP_LEVEL_INCLUDES

### ISSUE THREAD

**Issue by FeffyLaffy** [ZTzTopia/GTProxy#79]
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
CMake Error: CMAKE_PROJECT_TOP_LEVEL_INCLUDES file does not exist: C:/Users/anakbabi/Downloads/GTProxy-develop (1)/GTProxy-develop/cmake/cmake-conan/conan_provider.cmake
CMake Error at lib/CMakeLists.txt:1 (project):
  Language 'C' is currently being enabled.  Recursive call not allowed.

**Comment by ZTzTopia** [comment]
You need to use the `--recurse-submodules` flag when cloning as explained in https://github.com/ZTzTopia/GTProxy?tab=readme-ov-file#build

**Comment by FeffyLaffy** [comment]
> You need to use the `--recurse-submodules` flag when cloning as explained in https://github.com/ZTzTopia/GTProxy?tab=readme-ov-file#build

yeah forgor about that
