### ISSUE TITLE
Auto Collect?

### ISSUE THREAD

**Issue by zix3r** [ZTzTopia/GTProxy#8]
Hey, I noticed in the readme you had pathfinding for autocollect added or something like that, so how would I activate auto collect?

**Comment by ZTzTopia** [comment]
oh yeah, I forgot to re-add that feature because I just rewrite the pathfinding.

**Comment by zix3r** [comment]
Ah I see, well I'll be waiting for the update then

**Comment by zix3r** [comment]
@ZTzTopia could you compile the latest version? Whenever I try to do so it just throws this error:
![image](https://user-images.githubusercontent.com/43238887/171648331-3894f1ca-8a74-4f62-ba2f-ba9a16b78679.png)

**Comment by ZTzTopia** [comment]
Here is the download link for the latest program built from github actions:
https://github.com/ZTzTopia/GTProxy/suites/6763068940/artifacts/258648829

**Comment by zix3r** [comment]
@ZTzTopia Well, I downloaded this and I tried running but got a dll error:
![image](https://user-images.githubusercontent.com/43238887/171658320-c2960334-94fb-496d-a963-d31466b707e1.png)

After downloading the dll, it still threw an error, I have no idea what's causing it:
![image](https://user-images.githubusercontent.com/43238887/171658423-72cc8001-49a1-493b-ad5c-b32e23640345.png)

**Comment by ZTzTopia** [comment]
Have you installed [Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe)?

**Comment by zix3r** [comment]
@ZTzTopia, yes, I have. I reinstalled it just to check if it was the cause, but it's not it, still throws the same error.
Also, maybe you could add me on discord so the issue is fixed quicker? Only if you want to of course: zix#5205
